; ==================================
;  supervisor config file
; ==================================

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid            ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor             ; ('AUTO' child log dir, default $TEMP)
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

[program:celery]
command=scripts/run-celery-worker.sh
directory=/src/

user=root
numprocs=1
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
stdout_events_enabled = true
stderr_logfile=/dev/null
stderr_logfile_maxbytes=0
stderr_events_enabled = true

autostart=true
autorestart=true
startsecs=10

; Causes supervisor to send the termination signal (SIGTERM) to the whole process group.
stopasgroup=true

[program:superfsmon]
command=superfsmon -r *.py /src/sparkmeter celery

[eventlistener:stdout_redirect]
command = supervisor_stdout
buffer_size = 100
events = PROCESS_LOG
result_handler = supervisor_stdout:event_handler
