# Copyright (C) 2013-2017 SparkMeter, Inc.
# All Rights Reserved.
"""Add Scheduled load limits.

Revision ID: 0.56
Revises: 0.55
Create Date: 2018-01-16 16:34:04.565166

"""

import sqlalchemy as sa
from alembic import op

from sparkmeter.database.columns import JSONString

revision = '0.56'
down_revision = '0.55'


def upgrade():
    """Upgrade the database schema from 0.55 to 0.56."""
    op.alter_column('tariff', 'power_limit', new_column_name='flat_load_limit')
    op.add_column('tariff', sa.Column('load_limit_type', sa.String, nullable=True,
                                      server_default='flat'))
    op.add_column('tariff', sa.Column('load_limits', JSONString(), nullable=True,
                                      server_default='[]'))

    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.56 to 0.55."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    raise SystemExit("Downgrading from 0.56 to 0.55 not supported")
