# Copyright (C) 2013-2018 SparkMeter, Inc.
# All Rights Reserved.
"""Adjustable plan start day.

Revision ID: 0.61
Revises: 0.60
Create Date: 2018-08-17 17:10:57.622124

"""

import sqlalchemy as sa
from alembic import op

revision = '0.61'
down_revision = '0.60'


def upgrade():
    """Upgrade the database schema from 0.60 to 0.61."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        u'meter_billing', sa.Column('last_plan_expiration_date', sa.DateTime(), nullable=True))
    op.add_column(
        u'tariff',
        sa.Column('plan_start_day_of_month', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.61 to 0.60."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'meter_billing', 'last_plan_expiration_date')
    op.drop_column(u'tariff', 'plan_start_day_of_month')
    # ### end Alembic commands ###
