# Copyright (C) 2013-2018 SparkMeter, Inc.
# All Rights Reserved.
"""adds plan initial price to tariffs.

Revision ID: 0.62
Revises: 0.61
Create Date: 2018-08-26 01:31:27.571272

"""

import sqlalchemy as sa
from alembic import op

revision = '0.62'
down_revision = '0.61'


def upgrade():
    """Upgrade the database schema from 0.61 to 0.62."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        u'tariff',
        sa.Column('plan_fixed_fee', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.62 to 0.61."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tariff', 'plan_fixed_fee')
    # ### end Alembic commands ###
