# Copyright (C) 2013-2018 SparkMeter, Inc.
# All Rights Reserved.
"""Assign a length to the transaction memo field..

Revision ID: 0.68
Revises: 0.67
Create Date: 2019-01-31 07:47:21.890458

"""

import sqlalchemy as sa
from alembic import op

revision = "0.68"
down_revision = "0.67"


def upgrade():
    """Upgrade the database schema from 0.67 to 0.68."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS transaction_view")
    op.alter_column("transactions", "memo", type_=sa.String(300))
    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.68 to 0.67."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS transaction_view")
    op.alter_column("transactions", "memo", type_=sa.String())
    # ### end Alembic commands ###
