# Copyright (C) 2013-2019 SparkMeter, Inc.
# All Rights Reserved.
"""tariff_daily_energy_limit.

Revision ID: 0.74
Revises: 0.73
Create Date: 2019-09-12 18:13:05.100371

"""

import sqlalchemy as sa
from alembic import op

revision = '0.74'
down_revision = '0.73'


def upgrade():
    """Upgrade the database schema from 0.73 to 0.74."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('daily_energy_limit_enabled', sa.Boolean(), nullable=True))
    op.add_column('tariff', sa.Column('daily_energy_limit_reset_hour', sa.Integer(), nullable=True))
    op.add_column('tariff', sa.Column('daily_energy_limit_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.74 to 0.73."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff', 'daily_energy_limit_value')
    op.drop_column('tariff', 'daily_energy_limit_reset_hour')
    op.drop_column('tariff', 'daily_energy_limit_enabled')
    # ### end Alembic commands ###
