# Copyright (C) 2013-2019 SparkMeter, Inc.
# All Rights Reserved.
"""meter_daily_energy_limit.

Revision ID: 0.75
Revises: 0.74
Create Date: 2019-09-13 17:03:13.633257

"""

import sqlalchemy as sa
from alembic import op

revision = "0.75"
down_revision = "0.74"


def upgrade():
    """Upgrade the database schema from 0.74 to 0.75."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meter_billing", sa.Column("last_daily_energy_limit_reset_datetime", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "meter_billing", sa.Column("last_daily_energy_limit_reset_value", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.75 to 0.74."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meter_billing", "last_daily_energy_limit_reset_value")
    op.drop_column("meter_billing", "last_daily_energy_limit_reset_datetime")
    # ### end Alembic commands ###
