# Copyright (C) 2013-2026 SparkMeter, Inc.
# All Rights Reserved.
"""add user fs_uniquifier for Flask-Security-Too.

Revision ID: 0.83
Revises: 0.82
Create Date: 2026-03-27 00:23:16.934294

"""

import sqlalchemy as sa
from alembic import op

revision = '0.83'
down_revision = '0.82'


def upgrade():
    """Upgrade the database schema from 0.82 to 0.83."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fs_uniquifier', sa.String(length=255), nullable=True))
    op.execute("UPDATE \"user\" SET fs_uniquifier = replace(uuid_generate_v4()::text, '-', '')")
    op.alter_column('user', 'fs_uniquifier', nullable=False)
    op.create_unique_constraint(None, 'user', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():  # pragma: nocoverage
    """Downgrade the database schema from 0.83 to 0.82."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fs_uniquifier')
    # ### end Alembic commands ###
    raise SystemExit("Downgrading from 0.83 to 0.82 not supported")
